### ISSUE TITLE
Failed to resolve: im.crisp:crisp-sdk:0.0.4

### ISSUE THREAD

**Issue by anjar10** [crisp-im/crisp-sdk-android#1]
Is crisp maven accessible?
I try to download .aar file manually, but dl.bintray.com redirect it to http://akamai.bintray.com/ which can't be accessed.

**Comment by valeriansaliou** [comment]
Do you have any kind of corporate proxy on your network that may block the redirected URI?

**Comment by mywaystar** [comment]
Bintray is currently facing an outage. It will be back soon.
--

Baptiste Jamin
CEO, Crisp <https://crisp.im/> - Connect your customers to your team.

Le 20 juil. 2017 à 11:12, anjar10 <notifications@github.com> a écrit :

Is crisp maven accessible?
I try to download .aar file manually, but dl.bintray.com redirect it to http://akamai.bintray.com/ <http://akamai.bintray.com/> which can't be accessed.

**Comment by anjar10** [comment]
Thanks, finally I can build this app
