### ISSUE TITLE
Conflict with Glide Library

### ISSUE THREAD

**Issue by RHMDHDYT** [crisp-im/crisp-sdk-android#10]
Im using Glide 4.0.0 on my app while Crisp 0.0.17 using 3.x version of glide. And it crashed when i open a smiley emoticon on chat menu. When i check the gradle, Crisp override the glide module using latest version (4.0.0) when app compiled. How to avoid this conflict?

**Comment by mywaystar** [comment]
We released today a new version. It has been fixed.
