### ISSUE TITLE
Take photo feature

### ISSUE THREAD

**Issue by osman-teamswork** [crisp-im/crisp-sdk-android#100]
I am not able to click photo from camera in Android app, but in iOS app it is available to take photo from camera. Please check below screenshots from iOS and Android app for more details. 

Android screenshot--->
![clipboard-202203101758-ctpwu](https://user-images.githubusercontent.com/76420680/161697654-4642403f-7d42-4c65-9bb7-370ffda92982.png)

iOS screenshot--->
![clipboard-202203101755-layis](https://user-images.githubusercontent.com/76420680/161697669-45e2fd31-2d94-4dc7-bc35-2d073f8d86b7.png)

**Comment by Doc1faux** [comment]
The feature has been added in [`2.0.0beta1`](https://github.com/crisp-im/crisp-sdk-android/releases/tag/v2.0.0beta1).
This build is for preview as it still lacks some minor features and needs some optimizations :)
