### ISSUE TITLE
Crisp Persian language modification

### ISSUE THREAD

**Issue by rezafaraji93** [crisp-im/crisp-sdk-android#101]
Is it possible to set crisp language to persian? And also layout change to RTL

**Comment by Doc1faux** [comment]
Hi @rezafaraji93 and thank your for your feedback.

As reported in #62, SDK language is currently tied to device language and it is not currently planned to be adjustable.
The SDK currently supports persan language with RTL only if the device language is set to ;)

<img src="https://user-images.githubusercontent.com/2175246/161952363-066a1b06-bb8f-4fa4-a17c-2d4f9730d5c8.jpg" alt="screenshot" height="800">
