### ISSUE TITLE
Socket version to use

### ISSUE THREAD

**Issue by rezafaraji93** [crisp-im/crisp-sdk-android#102]
Do we still need to use socket version 1?

**Comment by Doc1faux** [comment]
Hi @rezafaraji93,

I tried this morning with the latest `v2.0.1` and it was working :o
I got the information from Crisp that the Socket.IO has been updated on the servers :)
So I plan the Socket.IO update on the next release ;)

While waiting, I still recommend [this workaround](https://github.com/crisp-im/crisp-sdk-android/issues/93#issuecomment-1037079048).

**Comment by Doc1faux** [comment]
@rezafaraji93  The new `1.0.11` release has just been pushed to mavenCentral with the latest Socket.IO `v2.0.1`. Just wait a couple of hours to be widely available ;)
