### ISSUE TITLE
Could not find permissionsdispatche.aar

### ISSUE THREAD

**Issue by atriarvin** [crisp-im/crisp-sdk-android#11]
Error:Could not find permissionsdispatcher.aar (com.github.hotchemi:permissionsdispatcher:2.4.0).
Searched in the following locations:
    https://jitpack.io/com/github/hotchemi/permissionsdispatcher/2.4.0/permissionsdispatcher-2.4.0.aar

What can i do with it ?

**Comment by mywaystar** [comment]
We released today a new version. It has been fixed.
