### ISSUE TITLE
Chat is empty :(

### ISSUE THREAD

**Issue by atriarvin** [crisp-im/crisp-sdk-android#12]
When i was chating to my self for test is has been working fine , but when i refreshed the app nothing showed in chat (app) and when i was trying to chat again , messages sent correctly but no message showed in app

**Comment by mywaystar** [comment]
Are you sure you are using the latest release?
--

Baptiste Jamin
CEO, Crisp <https://crisp.im/> - Connect your customers to your team.

On 31 Dec 2017, at 07:02, Arvin Atri <notifications@github.com> wrote:

When i was chating to my self for test is has been working fine , but when i refreshed the app nothing showed in chat (app) and when i was trying to chat again , messages sent correctly but no message showed in app
