### ISSUE TITLE
Crisp won't show in Android do not disturb exception menu

### ISSUE THREAD

**Issue by philippelarcher** [crisp-im/crisp-sdk-android#123]
Android lists application so we can select which are allowed to bypass the do not disturb mode.
Crisp won't show in this list.

**Comment by Doc1faux** [comment]
Hi @philippelarcher,

It seems you're talking about the app as the SDK does not include notifications.
If so, I let you reach the Crisp team @ https://crisp.chat/ as this repository is tied to the SDK ;)

**Comment by philippelarcher** [comment]
Crisp support gave me that link 😣

Le mar. 7 juin 2022 à 08:45, Sébastien Vitard ***@***.***> a
écrit :

**Comment by Doc1faux** [comment]
Erf :/

So I suppose it is really about the Crisp App...
I confirm that the current version of the app available on the Play Store does not show in the DND drop-down menu while the beta one (on which I am currently working) does.
I think this is just a notification channel configuration which has to be set on the current app.
I have passed the information to the Crisp team but I cannot assure you this will be fixed until the new app release :/

**Comment by Doc1faux** [comment]
I'm closing this issue which is not related to the Android SDK.
