### ISSUE TITLE
Get session ID from SDK 

### ISSUE THREAD

**Issue by harry-sm** [crisp-im/crisp-sdk-android#125]
Hello,  I'm not able to get the chat session id from the SDK. I want to use the session id with the the RTM API to get messages associated with that chat. Doing this allows me to push notifications even if the chat is not in the foreground.

**Comment by harry-sm** [comment]
Hello @Doc1faux 
Ultimately an onagentmessage event like the JS SDK would be optimal.

**Comment by baptistejamin** [comment]
Sounds good. Thanks for sharing! :)

**Comment by harry-sm** [comment]
@baptistejamin @Doc1faux 
Use case: The user is speaking with an agent in the app. The user leaves the chat screen and is on someone another screen I just want them to see an in-app message when the agent responds. So they can go back to the chat. that's it. An onagentmessage event would be perfect.

**Comment by Doc1faux** [comment]
Hi @harry-sm,

`String Crisp.getSessionIdentifier(Context)` public API has just been added to the new `1.0.15` release.
Its usage is equivalent to the [Web Chatbox SDK](https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/dollar-crisp/#get-session-identifier) one.

**Comment by baronha** [comment]
> Hi @harry-sm,
> 
> `String Crisp.getSessionIdentifier(Context)` public API has just been added to the new `1.0.15` release. Its usage is equivalent to the [Web Chatbox SDK](https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/dollar-crisp/#get-session-identifier) one.

I have a question?
How do I know CrispChat SDK has finished loading so I can get the sessionId.

**Comment by Doc1faux** [comment]
Hi @baronha,
Currently, Android SDK does not support event callbacks as the [Web SDK](https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/dollar-crisp/#register-a-callback-on-event) does.
However, it's clearly an area of improvements as it seems [iOS SDK](https://crisp-im.github.io/crisp-sdk-ios/documentation/crisp/crispsdk/addcallback(_:)) should support it too, but I did not found the registering method on the current `2.4.4` version.
I'll discuss of it with the team if and when we could add it to our roadmap.

**Comment by harry-sm** [comment]
Hey @baronha and @Doc1faux 

I agree that the callbacks from the Web SDK should be added to Android, IOS, and Flutter SDKs.

We weren't getting any in-app notifications with the mobile SDKs so we just added crisp via web view in our mobile app.
