### ISSUE TITLE
Inifite loop

### ISSUE THREAD

**Issue by mpopolin** [crisp-im/crisp-sdk-android#13]
Every second and later time I try to open the activity containing the CrispFragment, there is an infinite loop - the first load works perfectly, showing all messages and so on.
Tried with the example and the problem occurred as well.

**Comment by mywaystar** [comment]
Are you sure to have the latest release ?

**Comment by mpopolin** [comment]
Using 
 compile 'im.crisp:crisp-sdk:0.1.0'

**Comment by mywaystar** [comment]
Do you have any output in your logs?

**Comment by mpopolin** [comment]
Not really. Do you have some tag to filter the logs?
Filtering by crisp there is the following log for the first time only - nothing appears after the first:

01-03 08:51:24.318 18024 18024 I art     :   at android.view.View im.crisp.sdk.ui.CrispFragment.onCreateView(android.view.LayoutInflater, android.view.ViewGroup, android.os.Bundle) (SourceFile:59)
01-03 08:51:24.318 18024 18024 I art     :   at android.view.View im.crisp.sdk.ui.CrispFragment.onCreateView(android.view.LayoutInflater, android.view.ViewGroup, android.os.Bundle) (SourceFile:59)

**Comment by mywaystar** [comment]
Did you initiate properly the SDK? Can I can a copy of your initialisation script?

What is your android version?
--

Baptiste Jamin
CEO, Crisp <https://crisp.im/> - Connect your customers to your team.

On 3 Jan 2018, at 11:52, Marcel Cunha <notifications@github.com> wrote:

Not really. Do you have some tag to filter the logs?
Filtering by crisp there is the following log for the first time only - nothing appears after the first:

01-03 08:51:24.318 18024 18024 I art : at android.view.View im.crisp.sdk.ui.CrispFragment.onCreateView(android.view.LayoutInflater, android.view.ViewGroup, android.os.Bundle) (SourceFile:59)
01-03 08:51:24.318 18024 18024 I art : at android.view.View im.crisp.sdk.ui.CrispFragment.onCreateView(android.view.LayoutInflater, android.view.ViewGroup, android.os.Bundle) (SourceFile:59)

**Comment by mpopolin** [comment]
Yes, I think I did (the very first time I open the activity, everything works fine, the chat is loaded and so on - the problem just happens in the second and so on attempt).

```java
public class BaseApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        Crisp.initialize(this);
        Crisp.getInstance().setWebsiteId(BuildConfig.CRISP_KEY);
    }

```
And the Activity .xml layout:

```java
<?xml version="1.0" encoding="utf-8"?>

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:app="http://schemas.android.com/apk/res-auto"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:layout_behavior="@string/appbar_scrolling_view_behavior">

    <fragment
        android:name="im.crisp.sdk.ui.CrispFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_margin="0dp"
        android:tag="crisp_fragment"/>
</RelativeLayout>
```

**Comment by mywaystar** [comment]
What is the android version?
--

Baptiste Jamin
CEO, Crisp <https://crisp.im/> - Connect your customers to your team.

On 3 Jan 2018, at 12:15, Marcel Cunha <notifications@github.com> wrote:

Yes, I think I did (the very first time I open the activity, everything works fine, the chat is loaded and so on - the problem just happens in the second and so on attempt).

public class BaseApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        Crisp.initialize(this);
        Crisp.getInstance().setWebsiteId(BuildConfig.CRISP_KEY);
    }
And the Activity .xml layout:

<?xml version="1.0" encoding="utf-8"?>

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:app="http://schemas.android.com/apk/res-auto"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:layout_behavior="@string/appbar_scrolling_view_behavior">

    <fragment
        android:name="im.crisp.sdk.ui.CrispFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_margin="0dp"
        android:tag="crisp_fragment"/>
</RelativeLayout>

**Comment by mpopolin** [comment]
Android 7.1.1

**Comment by mpopolin** [comment]
@mywaystar not sure why yet (maybe flushing the queue wrongly for the second time?), but removing the static modifier from the isLoaded (and related methods) on CrispFragment solved the problem.

**Comment by mywaystar** [comment]
Could you chat with us on crisp.chat , I have very specific questions

**Comment by mpopolin** [comment]
Hi, started the chat but no responses.

**Comment by mywaystar** [comment]
It has been fixed. Thank you for your help!

**Comment by oliwmu** [comment]
Hi, 
I have the same issue, would be nice to have the way you solved this problem.
First activity launch,ok. Second activity launch, infinite loop error : 

_"[INFO:CONSOLE(1)] "Uncaught ReferenceError: initialize is not defined"
"INFO:CONSOLE(1)] "Uncaught TypeError: Cannot call method 'push' of undefined"_

sdk 0.1.14
