### ISSUE TITLE
Customization plugin support

### ISSUE THREAD

**Issue by yusrilsabir22** [crisp-im/crisp-sdk-android#136]
### The customization plugin didn't update on the mobile app

```
SDK version: 1.0.9
```

Thanks :)

**Comment by eliottvincent** [comment]
Hey there! Our mobile SDKs are not aware of plugins right now. Meaning that changes done in the Customization plugin don't impact the SDK chatbox.

This is definitely an area of improvements.

**Comment by Doc1faux** [comment]
Hi @yusrilsabir22 and thank your for your feedback.

Thanks @eliottvincent for replying 👍

**Comment by Doc1faux** [comment]
The feature has been added in [`2.0.0beta1`](https://github.com/crisp-im/crisp-sdk-android/releases/tag/v2.0.0beta1).
This build is for preview as it still lacks some minor features and needs some optimizations :)
