### ISSUE TITLE
NullPointerException on List.isEmpty()

### ISSUE THREAD

**Issue by Damien-L** [crisp-im/crisp-sdk-android#137]
Hello !

Just found a new issue :

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference
>        at im.crisp.client.internal.h.d.e(:2)
>        at im.crisp.client.internal.u.d$d.b(:6)
>        at im.crisp.client.internal.u.d$d.$r8$lambda$meaj1dg9MuxMgspZK3ldKlPjSSU()
>        at im.crisp.client.internal.u.d$d$$ExternalSyntheticLambda1.run(:4)
>        at android.os.Handler.handleCallback(Handler.java:883)
>        at android.os.Handler.dispatchMessage(Handler.java:100)
>        at android.os.Looper.loop(Looper.java:214)
>        at android.app.ActivityThread.main(ActivityThread.java:7417)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

Can you take a look ?
Thanks,

**Comment by Doc1faux** [comment]
Hi @Damien-L and thank you for your feedback.

Could you please precise me the version on which this crash happens?

**Comment by Damien-L** [comment]
1.0.12
I know there is now a new version : 1.0.13.
But i didn't find this problem, even in closed issue. So the problem is probable on 1.0.13 as well.

**Comment by Doc1faux** [comment]
That's fine, the clarification on the version was just to be able to symbolicate the stacktrace ;)
I will take a loot at it ;)

**Comment by Doc1faux** [comment]
@Damien-L I have just fixed the crash.
It will be available in the next `1.0.14` release.

I will let you know when it will be published ;)

**Comment by Doc1faux** [comment]
@Damien-L 1.0.14 fixing this issue has just been released.
It can take a few hours before it will be available.
I close the issue.
