### ISSUE TITLE
CrispSDK.searchHelpdesk() not implemented

### ISSUE THREAD

**Issue by nseb** [crisp-im/crisp-sdk-android#151]
HI , 
CrispSDK.searchHelpdesk() , and CrispSDK.openHelpdeskArticle() is not present in SDK Androd but  IOS Yes

**Comment by Doc1faux** [comment]
Hi @nseb and thank your for your feedback.
I already opened the #149 issue about the implementation of this feature.
This feature, as well as #100 and #118 are already planned for the next features milestone.
Unfortunately, I am currently focused on the Crisp Android app, so I cannot give you an ETA for the moment.
I close the issue as it is a duplicate.

**Comment by nseb** [comment]
@Doc1faux Thx
