### ISSUE TITLE
Duplicate Class Found

### ISSUE THREAD

**Issue by itssubhamroy23** [crisp-im/crisp-sdk-android#152]
Hi, Getting the error, kindly help resolve this.

Duplicate class androidx.lifecycle.ViewModelLazy found in modules jetified-lifecycle-viewmodel-ktx-2.3.1-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1) and lifecycle-viewmodel-2.5.0-runtime (androidx.lifecycle:lifecycle-viewmodel:2.5.0)
Duplicate class androidx.lifecycle.ViewTreeViewModelKt found in modules jetified-lifecycle-viewmodel-ktx-2.3.1-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1) and lifecycle-viewmodel-2.5.0-runtime (androidx.lifecycle:lifecycle-viewmodel:2.5.0)

![image](https://user-images.githubusercontent.com/83629415/222180251-74a205c8-19de-412a-ae3e-1dac0c9c6cfd.png)

**Comment by Doc1faux** [comment]
Hi @itssubhamroy23,

This is not a Crisp-SDK-Android related issue.
However, I already encountered this dependency duplicate error while developing the Crisp Android app.
It is due to the usage of `androidx.preference:preference` dependency after `android.preference` package deprecation.
I already reported the issue on [Google Issue Tracker](https://issuetracker.google.com/issues/238425626) but it will not be fixed...

The only fix is to exclude the problematic module from the `androidx.preference:preference` dependency as follow:
```
implementation('androidx.preference:preference:1.2.0') {
    exclude group: 'androidx.lifecycle', module:'lifecycle-viewmodel'
    exclude group: 'androidx.lifecycle', module:'lifecycle-viewmodel-ktx'
}
```

**Comment by itssubhamroy23** [comment]
Hi, Thanks for your reply.
But actually I am unav=ble to fix the issue even after putting the
implementation rules in the build.gradle file. Could you please help me fix
this issue?

**Comment by Doc1faux** [comment]
Unfortunately, I cannot help much more on this :/
The only advice I could give you is to find which of your dependencies use the outdated `androidx.lifecycle:lifecycle-viewmodel(-ktx):2.3.1` and add the exclude rules to them as I did when I had to switch between outdated `android.preference` package and the new dependency provided by Google `androidx.preference:preference:1.2.0`.
I know it's a pain in the ass to figure it out :/

**Comment by itssubhamroy23** [comment]
Thanks, Finally able to resolve that with just one line of code

implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0'

**Comment by itssubhamroy23** [comment]
By the way, I have few more issues with the app if you're the developer of
the same.

1. It takes a lot of time to deliver the message
2. I am using a high speed internet, still it's constantly showing "*Failed
to send. retry?*" It's really irritating sometimes.

Please fix those issues
