### ISSUE TITLE
Cannot resume chat activity whenever user minimize then click launcher icon

### ISSUE THREAD

**Issue by edomuhammad** [crisp-im/crisp-sdk-android#155]
Whenever user open my app and then open crisp then minimize it, then user click my app launcher icon, crisp suddenly disappeared, and my app going back to main activity. my expectation is, when user click my app launcher icon, it should be back to crisp not going back to main activity

https://github.com/crisp-im/crisp-sdk-android/assets/15313250/4c1636c6-b540-4a73-aa6c-b9cfaaab6b4b

**Comment by Doc1faux** [comment]
You can see both behavior in the Sample app of this repository and in the [Crisp app on the Play Store](https://play.google.com/store/apps/details?id=im.crisp.app).

The Sample app has its `LauncherActivity` launching in `standard` mode, so tapping the launcher icon just brings back the current task, with the chat running on top if started.

The Crisp app has  its `LauncherActivity` launching in `singleInstance` mode (for deep links and notifications handling), so tapping the launcher icon creates a new task with our `LauncherActivity` as it is more like a `SplashActivity`, re-routing to the correct root Activity or creating a stack (for conversation deep links) then killing itself.

**Comment by Doc1faux** [comment]
Hi @edomuhammad, did my replies helped you understand your issue?

As this issue is stale, I close it, I let you reopen it if needed ;)
