### ISSUE TITLE
Unable to prefil message to chatbox

### ISSUE THREAD

**Issue by nfonjeannoel** [crisp-im/crisp-sdk-android#160]
If it's possible to set photo of email or phone number, then shouldn't it be possible to set a prefil message when the chatbox is launched?
This is very useful feature but it doesn't seem to be available in the android SDK (read from conversations of some time back).

Just wondering, has anything been added which can help us achieve this desired behaviour?

Is there any walk around?

Any help here will be appreciated. Thanks

**Comment by Doc1faux** [comment]
Hi @nfonjeannoel,

Just to be sure, are you talking about an equivalent to the Web SDK [`$crisp.push(["set", "message:text", [message_text]])`](https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/dollar-crisp/#update-current-message-text) method?
If so, this feature is not yet available on mobile SDKs, but it could be added in a future release.
I pass the information to the team of your will to add it.

**Comment by nfonjeannoel** [comment]
Yes, that's what I'm referring to @Doc1faux 
I think it's a really useful and needed feature and will appreciate if it can be added. Thanks

**Comment by Doc1faux** [comment]
Hi @nfonjeannoel,

Just to let you know, I discussed with the team and this feature will not be released in the next mobile SDK release (`1.0.16` for Android) but is planned for a future one. I'll keep you up-to-date :)

**Comment by MouamleH** [comment]
Hello, any updates regarding this?

**Comment by Doc1faux** [comment]
Hi @MouamleH,

This feature was not prioritized for the moment but while checking callbacks feature on iOS for issue #172 which were documented but not accessible when I tested, I've just realized they were available for `Swift` but not `Objective-C` with which I've tested...
So I've seen that the `showMessage` method was already implemented on iOS... (see [doc](https://crisp-im.github.io/crisp-sdk-ios/documentation/crisp/crispsdk/showmessage(with:))).
I'll ask the team if I prioritize it for the next release.

However, with the #173 fix which seems a bit urgent, I'll probably release a new beta version this week with this and some new features but not this one.

I let you know of any update, as well as @nfonjeannoel ;)

**Comment by Doc1faux** [comment]
Hi @nfonjeannoel & @MouamleH,

Just to let you know that message prefill is planned for the next release :)

**Comment by Doc1faux** [comment]
Hi both of you, [`v2.0.4`](https://github.com/crisp-im/crisp-sdk-android/releases/tag/v2.0.4) with the [`message:show`](https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/dollar-crisp/#show-message-local-only) feature as just been released.
I let you read our [documentation](https://github.com/crisp-im/crisp-sdk-android/wiki/2.-Available-APIs#show-message-local-only) about it for implementation ;)

It should be available on `mavenCentral` in the next hours :)
