### ISSUE TITLE
Error in AppCompat fragments

### ISSUE THREAD

**Issue by ArtyomVoronov** [crisp-im/crisp-sdk-android#17]
It's impossible to use CrispFragment inside AppCompat fragments. Returning to a fragment with CrispFragment inside I have "Duplicate ID, tag null, or parent id with another fragment" error. 
Few workarounds exist and all of them require CrispFragment inheritance from android.support.v4.app.Fragment. For example, https://stackoverflow.com/a/19815266/4589148

Do you plan to implement CrispFragment for AppCompat?

**Comment by mywaystar** [comment]
Our example is using AppCompat, look at https://raw.githubusercontent.com/crisp-im/crisp-sdk-android/master/example/src/main/java/crisp/im/example/MainActivity.java

I think it's something else.

**Comment by ArtyomVoronov** [comment]
It works perfectly if you place CrispFragment inside activity. 
To reproduce it try to use CrispFragment inside fragment in AppCompatActivity. I'll show sample code tomorrow.

**Comment by mywaystar** [comment]
The example just above is using an AppCompatActivity

**Comment by ArtyomVoronov** [comment]
Yes, and your example works correct. The problem reproduces when using CrispFragment inside nested fragments inside an AppCompatActivity.

**Comment by mywaystar** [comment]
You can still inflate manually Note: 

> You cannot inflate a layout into a fragment when that layout includes a <fragment>. Nested fragments are only supported when added to a fragment dynamically.

**Comment by aazam-nouri** [comment]
And how to add that to a fragment dynamically?
