### ISSUE TITLE
Message received notification?

### ISSUE THREAD

**Issue by alexbusuioc** [crisp-im/crisp-sdk-android#172]
Notifications don't appear when a message is received.
How can users know they have a new message from support?
Is it possible to pull the number of unread messages?

**Comment by Doc1faux** [comment]
Hi @alexbusuioc,

Just to keep you up-to-date, the notification subject is currently discussed in the team about how we could implement it so the feature should come :)
However, don't expect it in the next release ;)

**Comment by Doc1faux** [comment]
Hi @alexbusuioc and @syauqy, we've added the notifications feature in the new [`v2.0.7`](https://github.com/crisp-im/crisp-sdk-android/releases/tag/v2.0.7) release.

It's a first draft so it currently opens the Activity declared as the main entry point of your app (see [wiki](https://github.com/crisp-im/crisp-sdk-android/wiki/3.-Notifications#33-open-the-chatbox-on-notification-tap)) but we're aiming to handle an optional Back Stack for you to open up any Activity you want to.
