### ISSUE TITLE
Undocumented limitations of session events' data

### ISSUE THREAD

**Issue by gekylafas** [crisp-im/crisp-sdk-android#177]
Through much trial-and-error, I (think I) have found some limitations about session events which, as far as I know, are not documented anywhere:

* sessions events cannot contain more than 10 pieces of data.
  By "pieces of data" I essentially mean that you cannot call `SessionEvent.setString()/setBool()/setInt()` more than 10 times in total for the same event.
  This may be a limitation only in iOS SDK, but still.
* The max length of a session event data **key** is 50
* Session event data keys can contain a limited range of characters (perhaps `[A-Za-z_]`???)
* The max length of a session event data **value** is 120

So, are those limitations true? Are there any other we should know about? Could you please document them somewhere so that we can avoid the guesswork?

**Comment by eliottvincent** [comment]
Hello @gekylafas :)

Yes those are real limitations. While they are not actually documented, they are explicitly returned by our API in case your data would be in conflict with one rule. Although I have to admit that if you use RTM, your data will be silently dropped, true.

Please find below the full list of limitations regarding `events`:
* text: max length 80
* 10 max properties
* key of each properties
  * must pass RegEx: `^([A-Za-z0-9_\\-]{1,50})$`
  * max length is 50

**Comment by gekylafas** [comment]
Hi @eliottvincent! Thank you for you answer!

I assume that "text: max length 80" refers to the name of the event, i.e. the first paramater of `SessionEvent`'s ctor, right?
Also, what about the value of each property? Is it true that its max length is 120?

Finally, should those limitations be added to the Android (& iOS) SDK's Wiki documentation or just left here in this issue?

**Comment by eliottvincent** [comment]
> I assume that "text: max length 80" refers to the name of the event
Yes true, it's the `text` property referred here: https://docs.crisp.chat/references/rest-api/v1/#add-a-people-event

> Also, what about the value of each property? Is it true that its max length is 120?
Yes, each value can either be a number, string or boolean, with a 120 length limit.

> Finally, should those limitations be added to the Android (& iOS) SDK's Wiki documentation or just left here in this issue?
Ideally yes, but we need to find a way to maintain these values up-to-date (in case of a change on our side) and that's why they are not documented right now :) We can't afford to maintain every validation rule by hand in multiple docs (JS SDK, iOS SDK, Android SDK, REST API, RTM API)
