### ISSUE TITLE
Reset Session Doesnt Work

### ISSUE THREAD

**Issue by siyanew** [crisp-im/crisp-sdk-android#18]
when I reset a session webview in Crisp Fragment freeze on loading, what should I do ?

**Comment by mywaystar** [comment]
Hello. This issue is now fixed.

Please update the SDK to the latest release.

**Comment by siyanew** [comment]
I Updated to `0.1.8` but it doesn't work. I Checked and you just add `isLoaded=False;` but it doesn't work again when I `Crisp.session.reset();` when i open that fragment again it freeze on loading.

**Comment by mywaystar** [comment]
Strange thing. I tested locally with a reset and it did work.
--

Baptiste Jamin
CEO, Crisp <https://crisp.im/> - Connect your customers to your team.

On 25 Jun 2018, at 16:57, Siavash <notifications@github.com> wrote:

I Updated to 0.1.8 but it doesn't work. I Checked and you just add isLoaded=False; but it doesn't work again when I Crisp.session.reset(); when i open that fragment again it freeze on loading.
