### ISSUE TITLE
Asking to set email on chat page 

### ISSUE THREAD

**Issue by dharmitaepaisa** [crisp-im/crisp-sdk-android#19]
I have set user email address through app using following method
 Crisp.User.setEmail(EMAIL_ID") 
, Still on live chat page , it is showing message as "please set your email to continue".

**Comment by roarapps** [comment]
any update on this?

**Comment by jinxac** [comment]
There is something going wrong with setEmail function. I observed when I updated email manually from UI it works fine, but when I open chat window for user on the app the email which I set earlier from UI gets cleared :/

**Comment by jinxac** [comment]
Hi @dharmitaepaisa, @roarapps 

Looks like with the active(or valid) email id it works fine. I don't know how crips checks for **valid** email, maybe the moderator could help us with it.

**Comment by moxspoy** [comment]
is there any solution for this?
