### ISSUE TITLE
Error: "string too large to encode using UTF-8 written instead as 'STRING_TOO_LARGE'" after updating Android API level from 33 to 34

### ISSUE THREAD

**Issue by ankithatwar** [crisp-im/crisp-sdk-android#191]
After updating the Android API level from 33 (Android 13) to 34 (Android 14), I have updated all required dependencies and configurations. However, upon syncing, cleaning, and rebuilding the project, I encountered the following error:
"string too large to encode using UTF-8 written instead as 'STRING_TOO_LARGE'."

**Comment by Doc1faux** [comment]
Hi @ankithatwar and thank you for your feedback,

What version of the SDK you're using and what string it concerns?
On our side, we use API 34 since last year and did not encounter any issue with strings too large and it has been a while since this issue has been fixed in `1.0.2`, see issue #41.

**Comment by ankithatwar** [comment]
Hi @Doc1faux 
Thank you for quick response.

I'm also using API 34 and gradle version is 8.5.2 latest one.
But getting this 
![image](https://github.com/user-attachments/assets/3d0f5b19-fe89-4bd6-a1cb-57fb60cb9626)
