### ISSUE TITLE
Edittext is not above keyboard after click

### ISSUE THREAD

**Issue by aderinto05** [crisp-im/crisp-sdk-android#20]
Edittext is not above keyboard after click, so I can find out what I type

**Comment by aderinto05** [comment]
![whatsapp image 2019-01-16 at 12 56 21](https://user-images.githubusercontent.com/40485371/51229234-31056b80-198e-11e9-991e-303aaf5c7bec.jpeg)

**Comment by mywaystar** [comment]
This should be fixed (it's a web rendering issue).

Could you confirm?

**Comment by ArnaudT** [comment]
@mywaystar where is it fixed ?
I can't see any code change in the repository. What version should I use ? 
the Latest commit fa5b37f  is from 31 Jul 2018.

In maven the latest version is from July.
https://mvnrepository.com/artifact/im.crisp/crisp-sdk/0.1.10

**Comment by mywaystar** [comment]
You can use the same version. Its a server side patch.
--

Baptiste Jamin
CEO, Crisp <https://crisp.im/> - Connect your customers to your team.

On 5 Feb 2019, at 17:24, Arnaud Tanguy <notifications@github.com> wrote:

@mywaystar <https://github.com/mywaystar> where is it fixed ?
I can't see any code change in the repository. What version should I use ?
the Latest commit fa5b37f <https://github.com/crisp-im/crisp-sdk-android/commit/fa5b37faf20a98f2e959688e3b6ca2c933e85ba7> is from 31 Jul 2018.

In maven the latest version is from July.
https://mvnrepository.com/artifact/im.crisp/crisp-sdk/0.1.10 <https://mvnrepository.com/artifact/im.crisp/crisp-sdk/0.1.10>

**Comment by ArnaudT** [comment]
It seems that it doesn't work for us as we tested it few hours ago before the new release and it didn't work and a user complained last Sunday.

**Comment by jinxac** [comment]
this is not working 0.1.11 also, can someone please help

**Comment by iceboy1369** [comment]
This is not working 0.1.13 too
