### ISSUE TITLE
notification show

### ISSUE THREAD

**Issue by saeedmpt** [crisp-im/crisp-sdk-android#22]
Does this SDK have the ability to display the notification on the user's handset?
If yes, how do I enable it?

**Comment by saeedmpt** [comment]
In my opinion, this source is not a notification feature. However, I found a solution with the help of firebase cloud messaging that you can send token firebase with the methods in this library and send with the help of that token to notification the user of a new message.

**Comment by baptistejamin** [comment]
Thank you for your feedbadk!
--

Baptiste Jamin
CEO, Crisp <https://crisp.im/> - Connect your customers to your team.

On 26 Feb 2019, at 03:21, saeedmpt <notifications@github.com> wrote:

In my opinion, this source is not a notification feature. However, I found a solution with the help of firebase cloud messaging that you can send token firebase with the methods in this library and send with the help of that token to notification the user of a new message.

**Comment by saeedmpt** [comment]
tnx

**Comment by Hoss3inf** [comment]
@saeedmpt would you please tell us about your approach to implementing notifications for the crisp SDK?

It would be a great help to me.
