### ISSUE TITLE
Migrate to support library or Android X fragments.

### ISSUE THREAD

**Issue by rafaelrodriguez342** [crisp-im/crisp-sdk-android#27]
Hello Guys Native Fragments has been deprecated we need this CrispFragment to Extend from a Support library fragment or an androidX fragment to be able to add it in Modern applications that uses architecture components etc.

**Comment by baptistejamin** [comment]
Hello!

We are not doing it right now as we are planning to make a new SDK, using native code this time 
--

Baptiste Jamin
CEO, Crisp <https://crisp.im/> - Connect your customers to your team.

On 19 Nov 2019, at 02:29, rafaelrodriguez342 <notifications@github.com> wrote:

Hello Guys Native Fragments has been deprecated we need this CrispFragment to Extend from a Support library fragment or an androidX fragment to be able to add it in Modern applications that uses architecture components etc.

**Comment by rwrz** [comment]
Any news on this?

**Comment by tobyworks** [comment]
Also wondering this

**Comment by 2BWorks** [comment]
I have made these changes, you can use it already:

allprojects {
        repositories {
            jcenter()
            maven { url "https://jitpack.io" }
        }
   }
   dependencies {
        implementation "com.github.2BWorks:crisp-sdk-android:master-SNAPSHOT"
   }

**Comment by rwrz** [comment]
Thank you. I will try this soon!
BTW, @baptistejamin, any news on the native SDK?

**Comment by baptistejamin** [comment]
We just published the early beta of the Crisp Android native SDK. You can find it here: https://github.com/crisp-im/crisp-sdk-android/tree/beta
