### ISSUE TITLE
Android notifications : persistent vibrator

### ISSUE THREAD

**Issue by Endalaust** [crisp-im/crisp-sdk-android#28]
Hi

It is not possible to manage notifications correctly on android, the vibrator is always present. 

Example: Each time a new message is received, the phone vibrates (even if no notification banners) and notifications are disabled.

More dangerous: If I lose the network for 2 hours and I receive 400 messages on Crisp during this time, when I regain network, my phone will vibrate 400 times for 20 minutes.

Right now my team had to uninstall Crisp from the android phones. No worries on iOS though.

Thanks.

**Comment by baptistejamin** [comment]
Hello!

Is it related to the Crisp Android App or the Crisp Mobile SDK?

**Comment by Endalaust** [comment]
Ah crap, Crisp Android App.. 
I asked where I can open issue on your crisp website, I haven't checked where Camille sent me.

**Comment by Endalaust** [comment]
Since we have changed all android phones, we don't have this issue anymore...
