### ISSUE TITLE
Native SDK Release?

### ISSUE THREAD

**Issue by walterholohan** [crisp-im/crisp-sdk-android#35]
Hey @baptistejamin, do you have any update on when the new android sdk will be released?

Thanks,
Walter

**Comment by baptistejamin** [comment]
It’s a matter of weeks :)
--

Baptiste Jamin
CEO, Crisp <https://crisp.im/> - Connect your customers to your team.

On 18 Sep 2020, at 09:16, Walter Holohan <notifications@github.com> wrote:


Hey @baptistejamin <https://github.com/baptistejamin>, do you have any update on when the new android sdk will be released?

Thanks,
Walter

**Comment by walterholohan** [comment]
Great stuff, If there is a beta release of the SDK I would be more than happy to test it out for you and try to integrate it into https://github.com/walterholohan/react-native-crisp-chat-sdk

**Comment by baptistejamin** [comment]
We just published the early beta of the Crisp Android native SDK. You can find it here: https://github.com/crisp-im/crisp-sdk-android/tree/beta
