### ISSUE TITLE
Stuck on Loading after reset session

### ISSUE THREAD

**Issue by Angelhandy** [crisp-im/crisp-sdk-android#36]
Hello!! we are working with version: im.crisp:crisp-sdk:0.1.15: when we reset session and then open CrispFragment agai it gets stuck on Loading, after that we close the activity and then open it again and then begins to work properly.

**Comment by eliottvincent** [comment]
Hello! You may want to use this version instead: https://github.com/crisp-im/crisp-sdk-android/tree/beta
We rewrote the SDK, it's now fully native. It's still in beta, but it works better than the old SDK version.
