### ISSUE TITLE
How to listen for new message for push notification in android sdk?

### ISSUE THREAD

**Issue by irkreja** [crisp-im/crisp-sdk-android#38]
How to listen for new message arrive for push notification in android sdk?

**Comment by baptistejamin** [comment]
Hi there! Unfortunately, that is not possible.

**Comment by irkreja** [comment]
Is it possible to keep old session even after session reset since session reset make the user always different user even if he use all details like email, mobile,name etc)?

**Comment by baptistejamin** [comment]
Sorry, what do you mean?

**Comment by irkreja** [comment]
![image](https://user-images.githubusercontent.com/25817831/109596242-0a8bf580-7b40-11eb-8ff0-24792ff01afa.png)
I used same details like email, mobile,name etc but it displaying as different user in inbox after session reset

**Comment by baptistejamin** [comment]
I see, if you want to have customers have one session, please check here. 


How to restore chat sessions with a token? — https://help.crisp.chat/en/article/how-to-restore-chat-sessions-with-a-token-c32v4t/
