### ISSUE TITLE
Unable to set tokenID

### ISSUE THREAD

**Issue by alenkopic1** [crisp-im/crisp-sdk-android#40]
Hi, 
there isn't method for setting tokenID.
For IOS there is a following method, but I can't find anything similar within Android SDK:
`CrispSDK.setTokenID(tokenID: "A_CUSTOM_ID")`
How can I set tokenID, using Crisp SDK for Android?
Best regards

**Comment by baptistejamin** [comment]
Hello there! Thanks for reaching out! It is indeed not yet supported on Android but no worries as the team is working on this one. Currently, we can only set nickname and set emails.

**Comment by FrantisekGazo** [comment]
There is `Crisp.setTokenID("A_CUSTOM_ID")`.

But I'm encountering crashes when I use it -> see logs: [logs.txt](https://github.com/crisp-im/crisp-sdk-android/files/6302381/logs.txt)
When I start our app 1st time, set token id and start chat everything works. But when I close and open chat I get a crash. And then every time I try to open a chat I get the same crash. That is until I reset session and use a different token ID. (but the crash shows again after a while and I have to use a new id again...)

**Comment by baptistejamin** [comment]
Hello

**Comment by baptistejamin** [comment]
Let me check this, could you let me know your email associated to Crisp and your website url please

**Comment by FrantisekGazo** [comment]
thanks. I set just a random email. do I have to use some email registrated on crisp?

**Comment by FrantisekGazo** [comment]
I'm using `franky3@ventrata.com`

**Comment by baptistejamin** [comment]
Thanks, let me forward this to the tech team and I will get back to you

**Comment by baptistejamin** [comment]
Can I ask you to post this issue on our Github project?

**Comment by FrantisekGazo** [comment]
do you mean as a separate issue in this repo?

**Comment by baptistejamin** [comment]
Yes a new issue please :)

**Comment by FrantisekGazo** [comment]
done https://github.com/crisp-im/crisp-sdk-android/issues/43

**Comment by baptistejamin** [comment]
Thanks, the dev team will review it as soon as they can :)

**Comment by eliottvincent** [comment]
Closing (duplicate with #43)
