### ISSUE TITLE
Getting STRING_TOO_LARGE error

### ISSUE THREAD

**Issue by alenkopic1** [crisp-im/crisp-sdk-android#41]
Hi, when I add Crisp dependency, with very next build I get an error "STRING_TOO_LARGE".
Here is a [video](https://drive.google.com/file/d/1Y7Y8gUDWrLrKpHMj0b3iTmjAR3p8azVe/view?usp=sharing). You can see that it starts with successful build. 
Right after adding Crisp dependency and repeating build, I get an error.

**Comment by baptistejamin** [comment]
What Gradle version are you using?

**Comment by adi9090** [comment]
Could this be related to large vector drawable files? The tile_floating_cogs.xml is 43.4kB file, tile_i_like_food.xml 11.1kB
Would it be better to use png in this cases?
This is suggested here: https://stackoverflow.com/a/60684722/5142327

**Comment by alenkopic1** [comment]
Hi, I'm using 4.0.1 Android Gradle Plugin Version, and 6.6.1 Gradle Version.

**Comment by baptistejamin** [comment]
Can you try downgrading Gradle?

**Comment by alenkopic1** [comment]
Hi, 
since it is a large project in production, downgrading Gradle is not an option.
Can you please solve this issue, maybe by removing oversized vector files?
Best regards,
Alen

**Comment by baptistejamin** [comment]
Sure, we'll have a look on this :)

**Comment by baptistejamin** [comment]
The setData and PushEvents are coming soon :)

**Comment by Doc1faux** [comment]
The issue was indeed related to too large vector drawable files.
The issue has been adressed in 1.0.2.

APIs have also been added in 1.0.2, check it [here](https://docs.crisp.chat/guides/chatbox-sdks/android-sdk/#availables-apis) :)
