### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.gson.JsonPrimitive.getAsString()' on a null object reference

### ISSUE THREAD

**Issue by FrantisekGazo** [crisp-im/crisp-sdk-android#43]
I'm encountering crashes when I use token id -> see logs: [logs.txt](https://github.com/crisp-im/crisp-sdk-android/files/6302706/logs.txt)

When I start our app 1st time, set token id and start chat everything works. But when I close and open chat I get a crash. And then every time I try to open a chat I get the same crash. That is until I reset session and use a different token ID. (but the crash shows again after a while and I have to use a new id again...)

There's nothing I can do on my side, can you help?

**Comment by FrantisekGazo** [comment]
I just discovered that the issue happens even when I don't set the token id.

After closing and opening a chat few time I see the same crash mentioned before.
And after restarting our app the sdk crashes on `Crisp.configure(...)` call.

**Comment by ollym** [comment]
hey @baptistejamin this is blocking a fairly major move we want to transition all our apps to Crisp. Is there any incentive we can offer to have this fixed this week?

**Comment by FrantisekGazo** [comment]
hi, any update on this?

**Comment by baptistejamin** [comment]
It happens only when using the Token_ID?

**Comment by FrantisekGazo** [comment]
no, I also tried it without the token id

**Comment by FrantisekGazo** [comment]
I only set these
```kotlin
Crisp.setUserNickname(user.name)
Crisp.setUserEmail(user.email)
if (user.phone != null) {
    Crisp.setUserPhone(user.phone)
}
if (user.company != null) {
    Crisp.setUserCompany(Company(user.company, null, null, null, null))
}
```
(our user name and email is always non-null)

And when I open chat, write a single message and then close chat and repeat this 3-times I get that crash when opening the chat for the 4rd time.
After that I get a crash everytime I run `Crisp.configure(context, config.key)` (I don't even get to opening the chat)

**Comment by alimcharaniya** [comment]
Facing the same issue currently.

**Comment by eliottvincent** [comment]
We just released a new version (1.0.3), it should fix the issue. Could you please give it a try and confirm?

**Comment by FrantisekGazo** [comment]
yes, 1.0.3 is working
Thanks :)

**Comment by eliottvincent** [comment]
Great news! Closing the issue then :)

**Comment by wahyuabid** [comment]
Hi guys i will get this issue after i sent an image in chat. Can you helo to solve this problem ?

**Comment by baptistejamin** [comment]
Hello crisp-sdk-android#43!

Angelique here, pleased to help you :)
