### ISSUE TITLE
Exit button is wayyy too small

### ISSUE THREAD

**Issue by ollym** [crisp-im/crisp-sdk-android#48]
Our QA team flagged an issue i think is valid, the close button to exit chat is way too small and hard to click. Attached is a screenshot and video.

![Image from iOS](https://user-images.githubusercontent.com/143771/116514801-cca31780-a8cb-11eb-9736-e8f35f8d7874.jpg)

https://user-images.githubusercontent.com/143771/116515005-070cb480-a8cc-11eb-9ad1-8e3655a87b66.mp4

**Comment by ollym** [comment]
And just now completely independent feedback from one our beta clients who tested this rollout:

![image](https://user-images.githubusercontent.com/143771/116673188-5e318880-a9a3-11eb-8869-0f4d4521635f.png)

**Comment by baptistejamin** [comment]
We will improve this on our next release :)
