### ISSUE TITLE
Bintray shutdown

### ISSUE THREAD

**Issue by alexghi** [crisp-im/crisp-sdk-android#49]
The binary that was hosted on bintray is no longer available as bintray is shutting down.
Could you provide us an alternative link to the SDK? @baptistejamin 

Thanks in advance

**Comment by wahyuabid** [comment]
move to mavencentral()
and downgrade version to 1.0.1
@alexghi

**Comment by eliottvincent** [comment]
Hey guys! We moved to Maven Central. We updated the SDK and the README :)
