### ISSUE TITLE
Custom layout

### ISSUE THREAD

**Issue by h4ppysmile** [crisp-im/crisp-sdk-android#6]
Crisp is good, but when is it possible to set custom layout for it through API?

**Comment by mywaystar** [comment]
Not planned
--

Baptiste Jamin
CEO, Crisp <https://crisp.im/> - Connect your customers to your team.

Le 10 août 2017 à 13:31, Hojat Modaresi Zade <notifications@github.com> a écrit :

Crisp is good, but when it is possible to set custom layout for it through API?
