### ISSUE TITLE
message layout

### ISSUE THREAD

**Issue by ThomasCoutardCV** [crisp-im/crisp-sdk-android#63]
Hello,

I think there is a problem with one layout in the Android SDK.
In ChatActivity, the last row of my message is not fully displayed

I reproduced this on multiple devices.
 
![Screenshot_20210719-104707](https://user-images.githubusercontent.com/54797261/126131673-02395a06-b85a-4876-a151-dd5918f48421.jpg)

Thanks :)

**Comment by eliottvincent** [comment]
Hello Thomas, thanks for reporting this issue! We'll look into that.

**Comment by ThomasCoutardCV** [comment]
Hello,

Can we have some news about this bug and maybe the fix ? :)

Thanks

**Comment by eliottvincent** [comment]
Hello, our Android developer is working full steam ahead on the brand new app, meaning that the SDK issues will be worked later.

**Comment by Doc1faux** [comment]
Also reproduced in #84 so I've closed it to keep only one issue.

**Comment by Doc1faux** [comment]
Hi @ThomasCoutardCV and thank you for your feedback :)
I add @francescogatto to our conversation as he also faced this issue more recently in #84.
I remember having faced this issue a long while ago and fixed it but it seems still there...
I struggle reproducing this issue, even with a very long list (both of yours concatenated)

<img src="https://user-images.githubusercontent.com/2175246/153647325-f59bcf9c-c358-44d9-b2a9-8068af886433.png" height="600" />

So I have many questions ^^"

- Which version of the SDK are you using?
- Is there a specific case where it happens? My use case was an bot message on the 1st message received by a visitor.

Thanks for your lights ;)

**Comment by ThomasCoutardCV** [comment]
Hello @Doc1faux,

The SDK version is 1.0.7.

My use case is also a bot workflow.
I reproduce it every time as you can see below :
![Screenshot_20220215-123120](https://user-images.githubusercontent.com/54797261/154054004-d02f3d71-f3e0-4e1f-8f4b-390cdc0a85d8.jpg)

**Comment by Doc1faux** [comment]
Thanks to confirm your feedback @ThomasCoutardCV.
Do you reproduce the bug on a specific version of Android or this happens on any?
I will have a closer look in the coming days, maybe with chained bot messages.

**Comment by ThomasCoutardCV** [comment]
Hello,

Many people using our chatbot are reporting it :/ So, on any version.

**Comment by Doc1faux** [comment]
This should be definitely fixed in [`2.0.0beta1`](https://github.com/crisp-im/crisp-sdk-android/releases/tag/v2.0.0beta1) as we now uses [`flexbox`](https://github.com/google/flexbox-layout) to display `picker choices`.
This build is for preview as it still lacks some minor features and needs some optimizations :)
