### ISSUE TITLE
setData methods

### ISSUE THREAD

**Issue by Angelhandy** [crisp-im/crisp-sdk-android#65]
Hi!! we have been using im.crisp:crisp-sdk:0.1.15 and we want to upgrade because of a bug that keeps the chat screen "on loading" when we reset the session, but in this new version 1.0.7 we can't find any type of: Crisp.Session.setData methods, and we use them for some operations. 

There is something like this in this new version?

**Comment by baptistejamin** [comment]
Hello! Thanks for sending this over, I have shared this question with the dev team and am hoping for an answer quickly.

**Comment by baptistejamin** [comment]
Hi again,

Would you please take a look at the final section in the README and let me know if that helps you, there are a few methods there which might help what you're trying to do!
