### ISSUE TITLE
Set custom placeholder/hint and default message feature

### ISSUE THREAD

**Issue by nilevia** [crisp-im/crisp-sdk-android#67]
is there any option to set custom placeholder or hint?
i update to version 1.0.7 and there's less option to customize the layout. I cant embed chat fragment anymore on my activity and can't set default message.

Another problem is, the chat activity always asking for email even i've set it using Crisp.setUserEmail()
Thanks.

**Comment by baptistejamin** [comment]
Currently, it's not possible to set a custom Placeholder.

About the setUserEmail, we will check about this :)

**Comment by Doc1faux** [comment]
Hi @nilevia and thanks for your feedback. Sorry for the late reply, I was working on the Crisp app rework :)
The issue about the chat activity still asking the email even after being set programmatically has been addressed in the recently released 1.0.9.
Let me know if you encounter it again.

Chat fragment has been in discussion and could come back in a future release :)

For placeholder/hint and default message, I don't know if this even planned for the moment.

**Comment by Doc1faux** [comment]
Setting custom Placeholder/hint and Default message features are parts of #136 one which will be available in the next release.
Closing this issue as duplicate.
