### ISSUE TITLE
Previous dialogue box isn't opening. Android/iOS app.  Crisp Free version

### ISSUE THREAD

**Issue by vasif3148** [crisp-im/crisp-sdk-android#71]
when user messages support but support not available. user close dialogue box. then support comes and answers question. but after that user comes again and opens dialogue box however This time user not opening previous dialogue box,he opens brand new one that's why he can't see support's answer

**Comment by Doc1faux** [comment]
Hi @vasif3148 and thank your for your feedback.
The issue has been addressed in 1.0.9.
I let you reopen it if you run into it again.
