### ISSUE TITLE
After Adding Crisp SDK, UI of my project is changed. UI Messed!

### ISSUE THREAD

**Issue by kishansolankiOpenxcell** [crisp-im/crisp-sdk-android#77]
@baptistejamin @eliottvincent @Doc1faux 

### Here is the screenshot of the app BEFORE ADDING CRISP SDK

![device-2021-10-08-091958](https://user-images.githubusercontent.com/59357271/136496731-7df087be-6c61-4676-a8e4-c90433bea148.png)

### And, here is the screenshot of the app AFTER ADDING CRISP SDK

![device-2021-10-08-094339](https://user-images.githubusercontent.com/59357271/136497332-54166861-4033-419a-bff2-5e5f319acbb1.png)

Let us know if anyone has faced this issue before and resolve it. With this issue, I can't integrate Crisp SDK.

Crisp Integrated SDK is:
implementation 'im.crisp:crisp-sdk:1.0.7'

It seems the issue is of the material library used in Crisp SDK. So how can one resolve this issue? I am not using Material Dependency in my project, but crisp is using it internally.

**Comment by Doc1faux** [comment]
Hi @kishansolankiOpenxcell and sorry to hear that.
Indeed, in our SDK, we are using `androidx.appcompat:appcompat` and `com.google.android.material:material` libraries.
With the recently released 1.0.9, I updated both libraries to latest.

All our res are prefixed with `crisp_` so it should not come from there.
Moreover, we define styles (also prefixed with `CrispTheme.` or `Crisp.`) only for theming:

- activity (no action bar/title, translucent status bar and color change),
- dialog (as well as activity + transparent background, not floating, no title),
- searchView (for text size)

And we apply them only to our activity & fragments so it should not come from here either.

I let you try the SDK update and come back to me if you still have this issue

**Comment by Doc1faux** [comment]
No feedback for a while, consider this as fixed, closing...
