### ISSUE TITLE
Chat not cleared

### ISSUE THREAD

**Issue by francescogatto** [crisp-im/crisp-sdk-android#82]
If the conversation is deleted from the web, in the sdk is still possible to see the conversation, even if the app is uninstalled and resetChatSession doesn't do nothing! 
PS I'm using the email of the customer as tokenid

**Comment by Doc1faux** [comment]
Hi @francescogatto and thank you for your feedback.
I discussed about it with @baptistejamin and the behavior is intended when `Crisp.setTokenID(String tokenID)` is used.
