### ISSUE TITLE
Chat is not displaying responses 

### ISSUE THREAD

**Issue by Angelhandy** [crisp-im/crisp-sdk-android#86]
Chat is not displaying messages in App, user can see their own messages but responses from chat team can't be seen in chat

**Comment by baptistejamin** [comment]
Hello there! We are sorry to hear about that. 

Just to verify, these are messages from agents to your customers using the app, that the customers can't see. Correct?

**Comment by Angelhandy** [comment]
Yes, exactly that. 

The user can send messages in chat and the agents can see them, but their agent responses can't be seen in the app chat

**Comment by baptistejamin** [comment]
Are the agents using the app or browser?

**Comment by Angelhandy** [comment]
They are using the web browser, it only happened once.

**Comment by baptistejamin** [comment]
I see, can you please send us screenshots?

**Comment by Angelhandy** [comment]
I already closed the session and re installed. But if it happens again I'll give you the information

**Comment by baptistejamin** [comment]
Thank you. Please keep us posted!
