### ISSUE TITLE
Have trouble about the different glide version.

### ISSUE THREAD

**Issue by hartviqb** [crisp-im/crisp-sdk-android#9]
I seen in your package module you are using glide version 2.7.0, but currently in my app i using glide newest version 4.0.0. 

the problem is i always got the error when i load giftmoticon

`E/AndroidRuntime:` FATAL EXCEPTION: main
Process: com.xxx.xxx, PID: 28874
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.xxx.xxx-2/split_lib_dependencies_apk.apk:classes75.dex)
  at im.crisp.sdk.ui.internals.adapters.CrispMessagesAdapter.a(SourceFile:298)
  at im.crisp.sdk.ui.internals.adapters.CrispMessagesAdapter.onBindViewHolder(SourceFile:120)`

i think it because the both our app using different glide version. 
Can u solve our problem? thanks...

**Comment by mywaystar** [comment]
We released today a new version. It has been fixed.
