### ISSUE TITLE
ChatActivity crash 

### ISSUE THREAD

**Issue by FoRRestDp** [crisp-im/crisp-sdk-android#91]
When a user opens `ChatActivity` for the first time and then immediately closes it a crash occurs. The stack trace of the crash is the following:

```
im.crisp.client.b.d.d.b.g (b.java:6)
im.crisp.client.b.d.d.b$a.intercept (b.java)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.kt:34)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.kt:95)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:83)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.kt:76)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.kt:201)
okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:517)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:919).
```
The cause of the crash is probably operator avatar loading. If activity is closed after the avatar is loaded, a crash does not occur. On the contrary, if it is closed immediately, the application crashes. One possible workaround for this crash is to start `ChatAcitivity` in another process using `android:process=":Chat"` tag on it in the manifest.

**Comment by Doc1faux** [comment]
Hi @FoRRestDp and thank your for your feedback.
Which version of the SDK are you using?
Trying to deobfuscate the stack trace, I presume you are under `1.0.7`?
If so, the underlying issue is not about operator avatar loading but is directly linked to #76 which has been fixed in 1.0.9.
I let you update the SDK an reopen the issue if you face the crash again.
