### ISSUE TITLE
Chat Activity connection issues 

### ISSUE THREAD

**Issue by Angelhandy** [crisp-im/crisp-sdk-android#92]
Hi!! 

We are having this the next message when trying to open ChatActivity:

"Error starting chat

We could not connect to the chat. Try again now, or later"

Last week was working fine

**Comment by Doc1faux** [comment]
Hi @Angelhandy and thank you for your feedback.
The support team brought to me your issue.
Has I discussed with them, I tried on my side to load the chat with your `websiteId` and I've faced no issue with the latest version 1.0.9 😕.

I then thought you could use the [Socket.IO-client Java](https://github.com/socketio/socket.io-client-java) in your app like in [this issue](https://github.com/crisp-im/crisp-sdk-android/issues/90).
So if this the case, I advise you to follow my steps to resolve it: https://github.com/crisp-im/crisp-sdk-android/issues/90#issuecomment-1036383513

At last, maybe you could share with me the SDK version you're using and the logs of the app when this issue occurs?

**Comment by Doc1faux** [comment]
In case you're using [Socket.IO-client Java](https://github.com/socketio/socket.io-client-java) in your app to connect to a Socket.IO v3.x+ server and a version downgrade on it is not desirable, if you have the hand on it, you can use the `allowEIO3: true` option on it as advised in https://github.com/crisp-im/crisp-sdk-android/issues/93#issuecomment-1037079048.

**Comment by Doc1faux** [comment]
Without news, I consider it fixed as #90 & #93, so I close it.
