### ISSUE TITLE
Crisp Socket version

### ISSUE THREAD

**Issue by rezafaraji93** [crisp-im/crisp-sdk-android#93]
I am using socket version 2 because my server side socket version is 4. But I have noticed in order to use crisp socket version 1 client side is needed. Is there any solution for this issue? I can not down grade my socket version to 1 because my app stops getting data from server.

**Comment by Doc1faux** [comment]
Hi @rezafaraji93, unfortunately, I have not the hand on the Socket.IO version used by the Crisp server and don't know if a migration to Socket.IO 3.x or 4.x is planned (cc @baptistejamin).
However, diving a bit into the [Socket.IO Java client documentation](https://socketio.github.io/socket.io-client-java/installation.html), if you have the hand on your server, it seems you could make your v4.x server backward compatible with the v1.x client with the `allowEIO3: true` option.
Hope it will help.

**Comment by rezafaraji93** [comment]
This solved the problem, thanks.
